server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
  port: 5000 # 배포 시 방화벽이 열려 있는 포트가 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohflixdb # AWS 호스트
    username: ohflix # AWS USERNAME
    password: ohflix1234 # AWS PASSWORD
  jpa:
    hibernate:
      ddl-auto: none # 배포 후 서버가 문제가 생기면 DB가 다시 만들어 지지 않도록 설정
    properties:
      hibernate:
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQLDialect # JPA 방언 설정
    open-in-view: false # true 는 세션이 서버에서 머물고 false 는 서비스에서 소멸한다.

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO # 배포하고 나면 INFO 부터 보면 된다.
    com.example.final_project: DEBUG # DEBUG 이상의 에러 뜨도록 설정
